### ISSUE TITLE
编译参考文献时，提示找不到thuthesis.bst文件

### ISSUE THREAD

**Issue by KuiWei004** [hust-latex/hustreport#5]
我看了texlive安装目录，thuthesis目录下只有thuthesis-author-year.bst以及thuthesis-numeric.bst

**Comment by KuiWei004** [comment]
我的版本是texlive 2019

**Comment by xu-cheng** [comment]
我更新了下模板，应该可以解决你的问题。

要注意的是目前这些模版都是没有人维护的。所以如果出现问题，需要你们自己解决。
